name: QuickShop
version: 4.5 #Beta
main: org.maxgamer.QuickShop.QuickShop
author: Netherfoam

description: Economy Shops plugin
website: http://maxgamer.org
softdepend: [Herochat, Vault, Spout]

commands:
    qs:
        description: QuickShop command
        usage: /qs
        aliases: [shop]
        
permissions:
    quickshop.create.sell:
        description: Allows a player to sell from a shop
        default: op
    quickshop.create.buy:
        description: Allows a player to buy from a shop
        default: op
    quickshop.create.double:
        description: Allows a player to create a double shop
        default: op
    quickshop.use:
        description: Allows a player to buy/sell using other players shops
        default: true
    quickshop.unlimited:
        description: Allows a Staff Member to use /qs unlimited and make a shop infinite
    quickshop.bypass.<itemID>:
        description: Allows a player to sell <itemID>, even if its blacklisted
    quickshop.other.destroy:
        description: Allows a Staff Member to destroy other players shops if they are locked in the config
    quickshop.other.open:
        description: Allows a Staff Member to open someone elses shop if they are locked in the config
    quickshop.other.price:
        description: Allows a Staff Member to change the price of someone elses shop
    quickshop.setowner:
        description: Allows a Staff Member to change the owner of any shop
    quickshop.find:
        description: Allows a player to locate the nearest shop of a specific item type. Works in a 3 chunk radius.
        default: true
    quickshop.refill:
        description: Allows a Staff Member to refill the shop theyre looking at with the given number of items.
        default: op
    quickshop.empty:
        description: Allows a Staff Member to empty the shop theyre looking at of all items.
        default: op
    quickshop.debug:
        description: Enables debug info to console
        default: op
    quickshop.export:
        description: Allows exporting database to mysql or sqlite
        default: op